In [ ]:
## DAT405 Assignment 5 - Group 52
<p>Hampus Jansson - (4 hrs)<p>
<p>Erik Johannesen - (4 hrs)<p>
    <p>May 9, 2023<p>

## Preprocessing
# 1.1
<p> One thing a model could base its prediction on is if certain key words have been used in the message by the sender. This could be words like; fortune, invest, crypto. Another factor could be that the sender's email adress is a known email adress that you have choosen previously to trust.<p>

## 2.2 a)
<p>CountVectorizer creates a matrix that shows the number of occurences of each unique token in a text. <p>

## 2.2 b)

<p>MultinomialNB looks at how many times a feature appears and BernoulliNB only looks at whether a feature appears or not. It lools like MultinomialNB performs slightly better in all the tests done here.<p>

## 3.1
<p>When the model is only trained on the easy hams, it performs well when tested on other easy hams.<p>

In [11]:
import pandas as pd
import os
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
import matplotlib.pyplot as plt
from sklearn.naive_bayes import BernoulliNB
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split


train_ham = []
test_ham = []
classifications_train = []
classifications_test = []
hard_X= []
hard_y =[]

X=[]
y=[]


entries = os.listdir('C:\\Users\\eriko\\Documents\\Python kurs\\New folder\\uppgift4\\easy_ham')

for i in range(0, len(entries)):
    
    with open('C:\\Users\\eriko\\Documents\\Python kurs\\New folder\\uppgift4\\easy_ham' + '\\' + entries[i]) as file:
        text = file.read()
        #train_ham.append(text)
        classifications_train.append('ham')
        X.append(text)
        y.append('ham')



entries = os.listdir('C:\\Users\\eriko\\Documents\\Python kurs\\New folder\\uppgift4\\spam')

for i in range(0, len(entries)):
    
    with open('C:\\Users\\eriko\\Documents\\Python kurs\\New folder\\uppgift4\\spam' + '\\' + entries[i], encoding ="iso-8859-1") as file:
        text = file.read()
        #train_spam.append(text)
        classifications_train.append('spam')
        X.append(text)
        y.append('spam')
        hard_X.append(text)
        hard_y.append('spam')
  

    
#temp = train_ham
#temp2 = test_ham
    
#for i in train_spam:
#    temp.append(i)

#for i in test_spam:
#    temp2.append(i)
    
    
vectorizer = CountVectorizer(max_features=40000)

    
vector_X = vectorizer.fit_transform(X).toarray() 

mnb = MultinomialNB()
bnb = BernoulliNB()

X_train, X_test, y_train, y_test = train_test_split(vector_X, y, test_size=0.5,random_state=0)

mnb.fit(X_train, y_train)
bnb.fit(X_train, y_train)

mpred = mnb.predict(X_test)
bpred = bnb.predict(X_test)

print("Score and confusion matrix for MultinomialNB: " + str(mnb.score(X_test, y_test)))
      
cm = confusion_matrix(y_test, mpred)
print(cm)

print("\nScore and confusion matrix for BernoulliNB: " + str(bnb.score(X_test, y_test)))
      
cm = confusion_matrix(y_test, bpred)
print(cm)

Score and confusion matrix for MultinomialNB: 0.9868938401048493
[[1275    1]
 [  19  231]]

Score and confusion matrix for BernoulliNB: 0.9344692005242464
[[1270    6]
 [  94  156]]


## 3.1 continued

<p>When the same model is tested on hard hams, it does not perform well and falsely classifies all the hard hams as spam.<p>
<p>This might be because the hard hams have more features in common with the spam than the easy hams does.<p>

In [12]:
entries = os.listdir('C:\\Users\\eriko\\Documents\\Python kurs\\New folder\\uppgift4\\hard_ham')

for i in range(0, int(len(entries))):
    
    with open('C:\\Users\\eriko\\Documents\\Python kurs\\New folder\\uppgift4\\hard_ham' + '\\' + entries[i]) as file:
        hard_X.append(text)
        hard_y.append('ham')
        X.append(text)
        y.append('ham')

hard_X = vectorizer.fit_transform(hard_X).toarray() 
        
mpred = mnb.predict(hard_X)
bpred = bnb.predict(hard_X)

print("Score and confusion matrix for MultinomialNB: " + str(mnb.score(hard_X, hard_y)))
      
cm = confusion_matrix(hard_y, mpred)
print(cm)

print("\nScore and confusion matrix for BernoulliNB: " + str(bnb.score(hard_X, hard_y)))
      
cm = confusion_matrix(hard_y, bpred)
print(cm)

Score and confusion matrix for MultinomialNB: 0.6644474034620506
[[  0 250]
 [  2 499]]

Score and confusion matrix for BernoulliNB: 0.6218375499334221
[[  0 250]
 [ 34 467]]


## 3.2
<p>When the model is trained on both hard and easy hams, it performs approximately as well as the easy ham model did with easy hams.<p>

In [13]:
vector_X = vectorizer.fit_transform(X).toarray() 

X_train, X_test, y_train, y_test = train_test_split(vector_X, y, test_size=0.5,random_state=0)

mnb.fit(X_train, y_train)
bnb.fit(X_train, y_train)

mpred = mnb.predict(X_test)
bpred = bnb.predict(X_test)

print("Score and confusion matrix for MultinomialNB: " + str(mnb.score(X_test, y_test)))
      
cm = confusion_matrix(y_test, mpred)
print(cm)

print("\nScore and confusion matrix for BernoulliNB: " + str(bnb.score(X_test, y_test)))
      
cm = confusion_matrix(y_test, bpred)
print(cm)

Score and confusion matrix for MultinomialNB: 0.9939430648092066
[[1390    7]
 [   3  251]]

Score and confusion matrix for BernoulliNB: 0.9672925499697154
[[1387   10]
 [  44  210]]


## 3.3

<p>Because headers and footers were included in the text, there might have been many features that came from there rather than from the messages. Much of that information was likely irrelevant because much of it is the same regardless of whether a mail is spam or not. Removing that information might lead to better performance. <p>